---
name: release
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: figure out new tag
        id: tag
        uses: anothrNick/github-tag-action@1.36.0
        env:
          WITH_V: false
          DRY_RUN: true # just want the version
          DEFAULT_BUMP: none

      - name: update galaxy.yml version
        run: |
          sed -i 's/version:.*/version: ${{ steps.tag.outputs.new_tag }}/' galaxy.yml
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}

      - name: set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}

      - name: install Ansible.i
        run: pip3 install ansible-core
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}

      - name: build collection
        run: ansible-galaxy collection build
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}

      - name: publish collection to galaxy
        run: >-
          ansible-galaxy collection publish
          krilor-oci-${{ steps.tag.outputs.new_tag }}.tar.gz
          --api-key ${{ secrets.GALAXY_API_KEY }}
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}

      - name: commit changes and push tag
        uses: EndBug/add-and-commit@v8
        with:
          author_name: GitHub Actions
          author_email: mail@example.com
          message: "[github action] releasing version v${{ steps.tag.outputs.new_tag }}"
          add: galaxy.yml
          tag: v${{ steps.tag.outputs.new_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.tag.outputs.new_tag != steps.tag.outputs.tag }}
